
GET http://localhost:8080/chat/Chloe
Content-Type: application/json

###

GET http://localhost:8080/chat/Joe
Content-Type: application/json

###

POST http://localhost:8080/chat/Chloe
Content-Type: application/json

{
  "message" : "Hi Joe!! How r u?"
}

###

POST http://localhost:8080/chat/Joe
Content-Type: application/json

{
  "message" : "Hi Joe!! How r u?"
}
